name = "ZircSat"
uuid = "3ff7f7d4-a092-4c5a-8094-e93df379e688"
authors = ["Lorenzo G. Candioti"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
